### ISSUE TITLE
Setup testing framework

### ISSUE THREAD

**Issue by mrbrianevans** [mrbrianevans/number-format-converter#1]
Need to write tests for conversion models

We could do test driven development where we write the tests first, and then make the models afterwards.

Ideally, we also want an automated test suite to run whenever we update the repo, to make sure nothing ever breaks. 

I'm not sure which framework is best to use. I've heard of jest and mocha, but don't know enough to decide.

**Comment by DanielRomeo** [comment]
i have also never used a framework for such although i think its a good idea. i'll do research too.

**Comment by mrbrianevans** [comment]
I have installed the mocha testing framework, set up the npm test script, and written a few example tests in the `test` folder
