### ISSUE TITLE
Setup for firebase

### ISSUE THREAD

**Issue by mrbrianevans** [mrbrianevans/number-format-converter#2]
Begin the process of connecting to firebase, and connecting the directory structure to firebase, ready for deployment when the project is ready.

**Comment by DanielRomeo** [comment]
Firebase is gonna require a gmail and both of us will have to know the credentials in order to login to the dashboard. meaning using a personal email is a No-go. should we create a new gmail specifically for this or?

**Comment by DanielRomeo** [comment]
I'll assign this to myself
