### ISSUE TITLE
Make contributors section on website

### ISSUE THREAD

**Issue by mrbrianevans** [mrbrianevans/number-format-converter#33]
#### Make a page on the frontend (or a section) to display the contributors to this repository to give them credit

To contribute, read the contribution docs [Contribution docs](https://github.com/mrbrianevans/number-format-converter/blob/master/contributing.md)

**Comment by castynet** [comment]
Hi, I'm taking a stab at this.

**Comment by DanielRomeo** [comment]
okay great, im assigning you.
