### ISSUE TITLE
Migrate the Project to Styled Components

### ISSUE THREAD

**Issue by castynet** [mrbrianevans/number-format-converter#34]
I'm working on the contributor's section #33. I'm in the styling part and as of now the project uses raw CSS for its styling, my proposition is to move the **entire project** to[ Styled Components](https://styled-components.com/). 
This will remove class conflicts that may arise in a project with more than one contributors, for instance you may have a class with the name **Wrapper** in the Contributors components, then someone else comes along and creates a new component and unknowingly uses the class name **Wrapper**, you could go through the whole project, record the classNames in use, then ensure that you avoid those, but that could get tiring esp. in a growing project. 
Styled components also allow Saas like; capabilities _"CSS with Superpowers..."_

I'm open to do the migration along with the styling I'm already doing, should you guys approve it.

**Comment by mrbrianevans** [comment]
Hi Riunge. 
Thank you, that proposal sounds good to me! I'm happy to sign off on that. Let's wait for @DanielRomeo to also approve, and then you're welcome to go ahead!

That will be much appreciated, and make future contribution easier.

**Comment by DanielRomeo** [comment]
Thanks @mrbrianevans , Hey @castynet ; Your suggestions sounds great. You're more than welcome to do that. Goodluck.

**Comment by castynet** [comment]
Great! I'm on it.

**Comment by DanielRomeo** [comment]
hey @castynet  the changes are now live here [https://number-format-converter-19ca7.web.app/](number-format-converter)
