### ISSUE TITLE
Limit output to JavaScripts max precision integer size

### ISSUE THREAD

**Issue by mrbrianevans** [mrbrianevans/number-format-converter#37]
When numbers become to big, JavaScript can no longer calculate them accurately, so it is giving incorrect output on very big numbers. We need some kind of limit on the input size of number to ensure results are always accurate

**Comment by castynet** [comment]
I've done some quick googling & this can be done by limiting the number of characters allowed in the input. The input could have a placeholder or the label saying the limit. 
With some JavaScript the input field could even show how many characters are remaining.

Is the limit needed for some conversions or is it needed for all the conversions?

**Comment by mrbrianevans** [comment]
Hi Riunge,
Yep, that sounds like what we need. The character limit showing on the input would be good. 
I think it will be a different amount of characters for the different number formats. For example, a binary number will be able to have more digits before reaching the MAX_INT than a base64 number. 

One way of doing it, would be to show a different character limit based on which format is selected. Or alternatively, it could display an error message if the max integer size was reached in the calculation.

**Comment by castynet** [comment]
I can't seem to find anything trustworthy on this, can you give me the limits for all the input types if you have them or maybe point me to a place I could find them...

**Comment by mrbrianevans** [comment]
The integer limit is accessible from the Number.MAX_SAFE_INTEGER constant.

I think the best way to tackle this is to check the decimal value during the calculation. 
After the input has been decoded to decimal, it should be compared to the MAX_INT constant, and only proceed with the function if it is less. Otherwise return an error message
