### ISSUE TITLE
Setup GitHub automations

### ISSUE THREAD

**Issue by mrbrianevans** [mrbrianevans/number-format-converter#4]
The process for a pull request getting added should be: 
1. Compile TypeScript
2. Run unit test suite
3. Check code quality and code style
4. Manual review of the PR
5. Accept and merge the PR to master
6. Repo uploads to firebase automatically

**Comment by mrbrianevans** [comment]
I have put a nodejs automation in. 

But it is throwing an error every run. For some reason it is looking in the wrong folder for package.json

**Comment by mrbrianevans** [comment]
The issue of running tests from the wrong directory is fixed. 

The tests are now running as expected, apart from mocha is throwing an error when called

**Comment by DanielRomeo** [comment]
Okay, Nice.
