### ISSUE TITLE
Cases when the app won't work

### ISSUE THREAD

**Issue by castynet** [mrbrianevans/number-format-converter#41]
The app doesn't seem to do any conversions.  The live version.

**Comment by DanielRomeo** [comment]
Hello fellow contributor @castynet , may you please be specific. I just tested the application now and it works. Is there perhaps something you identified that you would like to be specific about. 

I actually noticed that we have Base12 in the frontend although we haven't implemented it yet. It should be removed. I'm working on the algorithm for base12 right now actually. Is the base12 conversion what you are referring to?

**Comment by mrbrianevans** [comment]
Hi @castynet , 
I've inspected the production system logs and see that the web app failed on converting numbers with leading zeros. This is a known issue #38 , and has been addressed in [2cd4511](https://github.com/mrbrianevans/number-format-converter/commit/2cd45111810161f54ef1f5a4096c61a4b2d115a9), but not yet deployed.

Did you experience any other issues/failures to convert numbers (other than Duodecimal as mentioned above)?

Brian

**Comment by castynet** [comment]
I've done some further tests and it seems like you are right, the conversions only fail when the number starts with a zero. 
The English words conversion also seem to be broken.

**Comment by mrbrianevans** [comment]
Which conversion specifically fails with English words? Can you provide us with the input and the expected output, compared to the actual output if any.

**Comment by castynet** [comment]
this 
![image](https://user-images.githubusercontent.com/51113345/135669103-92e8cddd-ca63-4145-9cb2-7a482e41631e.png)

**Comment by mrbrianevans** [comment]
To clarify: the number format converter is expecting a number to convert, such as `sixty seven`. It cannot convert `hello` because thats not a number. It goes up to 1 million so won't be able to do numbers higher than that. If you find any other issues please let us know. Thanks

**Comment by castynet** [comment]
That does make sense... esp since its a 'number converter' could it throw an error though? or maybe convert it anyway?

**Comment by mrbrianevans** [comment]
Yes, it should throw an error. It does throw an error on the backend, and it sends the error message in the API response, but this is not shown in the user interface yet. Its a known issue documented under #16

**Comment by castynet** [comment]
Alright, If I find some time in the near future I could try and tackle either #16 or #38

**Comment by mrbrianevans** [comment]
Okay thanks for the feedback. I added error messages to the UI this morning to address #16 , and I am hoping to deploy the fix to #38 leading binary zeros soon (as mentioned earlier, the implementation is done but awaiting deploy).
